spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: teste
          uri: https://httpbin.org
          predicates:
          - Path=/get/**
          filters:
          - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: refresh