spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: external-api
          uri: http://http://sped.rfb.gov.br/
          predicates:
            - Path=/api/externa/**
          filters:
            - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: "*"