spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: teste
          uri: https://httpbin.org/get
          predicates:
          - Path=/teste
          filters:
          - RewritePath=/teste, /

management:
  endpoints:
    web:
      exposure:
        include: "*"