spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: external-api
          uri: http://sped.rfb.gov.br/
          predicates:
            - Path=/sped/**
          filters:
            - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: refresh