spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: testeHttpbin
          uri: https://httpbin.org
          predicates:
          - Path=/teste
          filters:
          - SetPath=/get

management:
  endpoints:
    web:
      exposure:
        include: "*"