######################################################################################## 
# @name authRequest
POST http://localhost.com.br/auth/realms/fachesf-ad/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=sgprev
&client_secret=15cNOErHE0s2fZIBdZq0SdBa93YqXScf

### Ativar a capacidade de atualizar as rotas sem reiniciar o Gateway, usando o endpoint:
POST http://localhost:8080/actuator/refresh
Content-Type: application/json
Authorization: Bearer {{authRequest.response.body.access_token}}

###
GET http://localhost:8080/actuator/gateway/routes
Authorization: Bearer {{authRequest.response.body.access_token}}