spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: external-api
          uri: https://api.externa.com
          predicates:
            - Path=/api/externa/**
          filters:
            - StripPrefix=2