server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_GIT_URI}
          default-label: main
          search-paths: .
          force-pull: true
          timeout: 10000
          username: ${CONFIG_SERVER_GIT_USERNAME}
          password: ${CONFIG_SERVER_GIT_PASSWORD}
management:
  endpoints:
    web:
      exposure:
      include: "*"
  endpoint:
    refresh:
      access: unrestricted
